server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
        #application的值就是注册中心服务的名称，客户端通过这个名称找到事务处理的服务，可以自己定义，但需要注意的是，file:
        #conf中的，service里边配置的事务组应该跟服务名保持一致
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
